{{- if .Values.kafkaui.enabled -}}
{{- $namespace := .Release.Namespace -}}
{{- $release := .Release.Name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "{{ $release }}-cluster"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "{{ $release }}-broker-0.{{ $release }}-broker-headless.{{ $namespace }}.svc.cluster.local:9092,{{ $release }}-broker-1.{{ $release }}-broker-headless.{{ $namespace }}.svc.cluster.local:9092,{{ $release }}-broker-2.{{ $release }}-broker-headless.{{ $namespace }}.svc.cluster.local:9092"
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: "{{ $release }}-zookeeper.{{ $namespace }}.svc.cluster.local:2181"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/kafka-ui"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8090   
      targetPort: 8080
  type: ClusterIP
---
{{- if .Values.kafkaui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.kafkaui.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.kafkaui.ingress.host }}
      http:
        paths:
          - path: /kafka-ui
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 8090
{{- end -}}
{{- end -}}